# Generated by Django 3.0.5 on 2020-04-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('video', models.URLField(blank=True, max_length=1084, null=True, verbose_name='Video')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.Author', verbose_name='Author')),
            ],
        ),
    ]
