# Generated by Django 3.0.5 on 2020-04-14 04:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20200414_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
    ]
