# Generated by Django 3.0.5 on 2020-04-14 04:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=models.CharField(max_length=255, null=True, unique=True, verbose_name='Title'), unique=True),
        ),
    ]
