# Generated by Django 3.0.5 on 2020-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_description_pagetype_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetype',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='pagetype',
            name='descriptions',
            field=models.ManyToManyField(to='cooking.Description'),
        ),
    ]
