# Generated by Django 3.0.5 on 2020-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_auto_20200414_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
