# Generated by Django 3.0.5 on 2020-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0010_auto_20200414_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='items',
        ),
        migrations.AddField(
            model_name='navigation',
            name='items',
            field=models.ManyToManyField(to='cooking.NavItem'),
        ),
    ]
