# Generated by Django 3.0.5 on 2020-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_auto_20200414_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.URLField(max_length=1084, null=True),
        ),
    ]
