# Generated by Django 3.0.5 on 2020-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0012_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Youtube', 'Youtube'), ('Instagram', 'Instagram'), ('Discord', 'Discord'), ('Twitch', 'Twitch'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook')], max_length=255, null=True, unique=True),
        ),
    ]
