# Generated by Django 3.0.5 on 2020-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0013_auto_20200414_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socials', models.ManyToManyField(to='cooking.Social')),
            ],
        ),
    ]
