# Generated by Django 3.0.5 on 2020-04-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0014_auto_20200414_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
