# Generated by Django 3.0.5 on 2020-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0015_delete_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
