# Generated by Django 3.0.5 on 2020-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0016_auto_20200415_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
