# Generated by Django 3.0.5 on 2020-04-15 19:22

import cooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0017_recipe_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cooking.models.get_recipe_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
