# Generated by Django 3.0.5 on 2020-04-22 14:42

import cooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0020_auto_20200421_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=cooking.models.get_recipe_image, verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, max_length=1084, null=True, verbose_name='Video(optional)'),
        ),
    ]
